Repository codestates-seb/seb40_main_016, pull requests merged in 2022-11, with the labels that each got.

#8 be. 예외처리 관련 초기 세팅
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/cocoa/catdog/exception/BusinessLogicException.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/response/ErrorResponse.java
Labels: [BE] 김정민, [BE] 조지선, [BE] 남상욱

#9 Be.feat mapping
  client/src/App.jsx
  client/src/index.jsx
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/cocoa/catdog/CatdogApplication.java
  server/src/main/java/com/cocoa/catdog/ServletInitializer.java
  server/src/main/java/com/cocoa/catdog/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/entity/Like.java
  server/src/main/java/com/cocoa/catdog/article/entity/Report.java
  server/src/main/java/com/cocoa/catdog/article/entity/Tag.java
  server/src/main/java/com/cocoa/catdog/audit/AuditingEntity.java
  server/src/main/java/com/cocoa/catdog/comment/entity/Comment.java
  server/src/main/java/com/cocoa/catdog/comment/entity/CommentLike.java
  server/src/main/java/com/cocoa/catdog/comment/entity/CommentReport.java
  server/src/main/java/com/cocoa/catdog/exception/BusinessLogicException.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/item/entity/Item.java
  server/src/main/java/com/cocoa/catdog/order/entity/Order.java
  server/src/main/java/com/cocoa/catdog/order/entity/OrderItem.java
  server/src/main/java/com/cocoa/catdog/response/ErrorResponse.java
  server/src/main/java/com/cocoa/catdog/user/entity/Follow.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/GiveTake.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java
  server/src/main/resources/application.yml
  server/src/test/java/com/appstew/practiceMain/PracticeMainApplicationTests.java
Labels: ✨ feature, [BE] 김정민, [BE] 조지선, [BE] 남상욱

#13 [Client] 컨테이너 컴포넌트 제작
  client/src/components/InnerContainer/InnerContainer.tsx
  client/src/components/OuterContainer/OuterConainer.tsx
Labels: ✨ feature, [FE] 이수련, 💄 style

#17 [Client] 버튼 컴포넌트 제작
  client/src/assets/style/GloabalVariables.ts
  client/src/components/Button.tsx
Labels: ✨ feature, [FE] 김윤희, 💄 style

#20 [Client] 인풋 컴포넌트 제작
  client/src/assets/style/GloabalVariables.ts
  client/src/components/Input.tsx
Labels: ✨ feature, [FE] 김윤희, 💄 style

#21 [Client] headerBefore 컴포넌트 제작
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/HeaderBefore.tsx
Labels: ✨ feature, [FE] 송인선

#24 [Client] 이미지카드 컴포넌트 제작
  client/src/components/ImageCard/ImageCard.tsx
Labels: ✨ feature, [FE] 김윤희, 💄 style

#25 [Client] 인풋 컴포넌트 수정
  client/src/components/Input/Input.tsx
  client/src/components/Input/style.ts
Labels: [FE] 김윤희, ♻️ refactor

#26 [Client] 버튼 컴포넌트 수정
  client/src/components/Button/Button.tsx
  client/src/components/Button/style.ts
Labels: [FE] 김윤희, ♻️ refactor

#27 [Client] headerAfter 컴포넌트 제작
  client/src/App.tsx
  client/src/components/HeaderAfter.tsx
Labels: ✨ feature, [FE] 송인선

#29 [Client] avatar 컴포넌트 제작
  client/public/default-avatar-bg.png
  client/src/components/Avatar/Avatar.tsx
  client/src/components/Avatar/style.ts
Labels: ✨ feature, [FE] 이수련, 💄 style

#34 [Client] header 컴포넌트 라우터 연결
  client/src/components/Header/HeaderAfter.tsx
  client/src/components/Header/HeaderBefore.tsx
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/Shop/Shop.tsx
Labels: ✨ feature, [FE] 송인선, 💄 style

#36 [Server] 로그인, JWT, 팔로우 기능 구현
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/CatdogApplication.java
  server/src/main/java/com/cocoa/catdog/ServletInitializer.java
  server/src/main/java/com/cocoa/catdog/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/cocoa/catdog/audit/AuditingEntity.java
  server/src/main/java/com/cocoa/catdog/auth/CustomAuthorityUtils.java
  server/src/main/java/com/cocoa/catdog/auth/ErrorResponder.java
  server/src/main/java/com/cocoa/catdog/auth/LoginDto.java
  server/src/main/java/com/cocoa/catdog/auth/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/cocoa/catdog/auth/filter/JwtVerificationFilter.java
  server/src/main/java/com/cocoa/catdog/auth/handler/UserAccessDeniedHandler.java
  server/src/main/java/com/cocoa/catdog/auth/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/com/cocoa/catdog/auth/handler/UserAuthenticationFailureHandler.java
  server/src/main/java/com/cocoa/catdog/auth/handler/UserAuthenticationSuccessHandler.java
  server/src/main/java/com/cocoa/catdog/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/cocoa/catdog/auth/userdetails/UsersDetailsService.java
  server/src/main/java/com/cocoa/catdog/config/SecurityConfiguration.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/item/entity/Item.java
  server/src/main/java/com/cocoa/catdog/response/ErrorResponse.java
  server/src/main/java/com/cocoa/catdog/response/MultiResponseDto.java
  server/src/main/java/com/cocoa/catdog/response/PageInfo.java
  server/src/main/java/com/cocoa/catdog/response/SingleResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/controller/FollowController.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/FollowResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserPatchDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserPostDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/entity/Follow.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/mapper/FollowMapper.java
  server/src/main/java/com/cocoa/catdog/user/mapper/UserMapper.java
  server/src/main/java/com/cocoa/catdog/user/repository/FollowRepository.java
  server/src/main/java/com/cocoa/catdog/user/repository/UserRepository.java
  server/src/main/java/com/cocoa/catdog/user/service/FollowService.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java
  server/src/main/resources/application-h2.yml
  server/src/main/resources/application-ori.yml
  server/src/main/resources/application.yml
Labels: ✨ feature, [BE] 김정민

#38 [Server] 글 관련 기능 추가
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/Dto/PageInfo.java
  server/src/main/java/com/cocoa/catdog/article/Dto/PageResponseDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/repository/ArticleRepository.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserDto.java
  server/src/main/java/com/cocoa/catdog/user/repository/UserRepository.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/GiveTake.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java
  server/src/main/resources/application.yml
Labels: ✨ feature, [BE] 조지선

#39 [Client] footer 컴포넌트 제작
  client/src/App.tsx
  client/src/components/Footer/Footer.tsx
Labels: ✨ feature, [FE] 송인선

#40 [Server] 코멘트 관련 기능 추가
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/entity/Like.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java
  server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentDto.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
  server/src/main/java/com/cocoa/catdog/comment/entity/Comment.java
  server/src/main/java/com/cocoa/catdog/comment/entity/CommentLike.java
  server/src/main/java/com/cocoa/catdog/comment/entity/CommentReport.java
  server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java
  server/src/main/java/com/cocoa/catdog/comment/repository/CommentRepository.java
  server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/item/entity/Item.java
  server/src/main/java/com/cocoa/catdog/order/entity/Order.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/repository/UserRepository.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java
  server/src/main/resources/application.yml
  server/src/main/resources/application3.yml
  server/src/test/java/com/appstew/practiceMain/comment/CommentServiceUnitTest.java
Labels: ✨ feature, [BE] 남상욱, ✅ test

#41 [Client] header, footer 컴포넌트 css 수정
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/HeaderAfter.tsx
  client/src/components/Header/HeaderBefore.tsx
Labels: [FE] 송인선, 💄 style

#42 🐛 fix : 전체적인 수정 실행완료 확인
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/order/controller/OrderController.java
  server/src/main/java/com/cocoa/catdog/order/dto/OrderDto.java
  server/src/main/java/com/cocoa/catdog/order/dto/OrderItemDto.java
  server/src/main/java/com/cocoa/catdog/order/dto/OrderResponseDto.java
  server/src/main/java/com/cocoa/catdog/order/entity/Order.java
  server/src/main/java/com/cocoa/catdog/order/entity/OrderItem.java
  server/src/main/java/com/cocoa/catdog/order/mapper/OrderMapper.java
  server/src/main/java/com/cocoa/catdog/order/repository/OrderRepository.java
  server/src/main/java/com/cocoa/catdog/order/service/OrderService.java
  server/src/main/java/com/cocoa/catdog/repository/ArticleRepository.java
  server/src/test/java/com/appstew/practiceMain/comment/CommentServiceUnitTest.java
Labels: 🐛 bug, [BE] 김정민, [BE] 조지선, [BE] 남상욱

#43 [Client] 모달 컴포넌트 타이틀영역 버튼 다양화
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/style.ts
Labels: ✨ feature, [FE] 이수련, ♻️ refactor, 💄 style

#45 [Client] menulist 컴포넌트 제작
  client/src/components/Header/HeaderAfter.tsx
  client/src/components/Header/MenuList.tsx
  client/src/pages/Signup/Signup.tsx
Labels: ✨ feature, [FE] 송인선

#48 [Server] 백엔드 2차 취합 전 appstew PR 입니다
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/auth/jwt/JwtTokenizer.java
  server/src/main/java/com/cocoa/catdog/dto/MultiResponseDto.java
  server/src/main/java/com/cocoa/catdog/dto/PageInfo.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java
Labels: ✨ feature, ♻️ refactor

#51 [Client] 회원가입 페이지 1차 제작
  client/src/assets/img/boy-icon.svg
  client/src/assets/img/cat-icon.svg
  client/src/assets/img/dog-icon.svg
  client/src/assets/img/finger-one-symbol.svg
  client/src/assets/img/finger-two-symbol.svg
  client/src/assets/img/human-icon.svg
  client/src/components/Gender/Gender.tsx
  client/src/components/Gender/style.ts
  client/src/components/SignupFormStep/StepForm.tsx
  client/src/components/SignupFormStep/style.ts
  client/src/components/SignupTypeStep/StepType.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/style.ts
  client/src/utills/BirthYearCheck.ts
  client/src/utills/Regex.ts
Labels: ✨ feature, [FE] 이수련, 💄 style

#53 [Client] sortTab 컴포넌트 제작
  client/src/components/SortTab/SortTab.tsx
Labels: ✨ feature, [FE] 송인선

#58 [Client] main 페이지 레이아웃 구현 및 더미데이터 추가
  client/src/pages/Main/DummyData.ts
  client/src/pages/Main/Main.tsx
Labels: ✨ feature, [FE] 송인선

#56 Be.feat mysql
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java
  server/src/main/java/com/cocoa/catdog/comment/entity/CommentReport.java
  server/src/main/java/com/cocoa/catdog/item/controller/ItemController.java
  server/src/main/java/com/cocoa/catdog/item/service/ItemService.java
  server/src/main/java/com/cocoa/catdog/order/controller/OrderController.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
  server/src/test/java/com/cocoa/catdog/CatdogApplicationTest.java
  server/src/test/java/com/cocoa/catdog/comment/CommentServiceUnitTest.java
Labels: 🐛 bug, ✨ feature, [BE] 남상욱

#60 [Server] Cors 에러 해결 및 유저 팔로우 상태 확인/생일 유저 조회 API 추가
  server/src/main/java/com/cocoa/catdog/config/CorsFilter.java
  server/src/main/java/com/cocoa/catdog/config/SecurityConfiguration.java
  server/src/main/java/com/cocoa/catdog/user/controller/FollowController.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserBirthDto.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/mapper/UserMapper.java
  server/src/main/java/com/cocoa/catdog/user/repository/UserRepository.java
  server/src/main/java/com/cocoa/catdog/user/service/FollowService.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
Labels: ✨ feature, [BE] 김정민

#62 [Client] imageCard 컴포넌트 및 메인페이지 css 수정
  client/src/components/ImageCard/ImageCard.tsx
  client/src/pages/Main/Main.tsx
Labels: [FE] 송인선, 💄 style

#63 ✨feat: 회원가입 api 연결 및 결과 알림 컴포넌트 작성
  client/.gitignore
  client/src/api/api.ts
  client/src/assets/img/finger-three-symbol.svg
  client/src/components/Gender/Gender.tsx
  client/src/components/SignupFormStep/StepForm.tsx
  client/src/components/SignupSuccessStep/StepSucess.tsx
  client/src/components/SignupTypeStep/StepType.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/style.ts
  client/src/types/user.ts
Labels: ✨ feature, [FE] 이수련, 💄 style

#69 [Client] 로그인 페이지 기본 완성
  client/package-lock.json
  client/package.json
  client/public/assets/cat-selfie-clipart.png
  client/public/assets/default-avatar-bg.png
  client/public/assets/dog-with-snack-clipart.png
  client/public/assets/user-clipart.png
  client/src/App.tsx
  client/src/assets/img/exchange-desc.svg
  client/src/assets/img/github-icon.svg
  client/src/assets/img/give-snack-desc.svg
  client/src/assets/img/google-icon.svg
  client/src/assets/img/naver-icon.svg
  client/src/assets/img/upload-desc.svg
  client/src/assets/style/GloabalVariables.ts
  client/src/components/Avatar/style.ts
  client/src/components/LoginForm/LoginForm.tsx
  client/src/components/LoginForm/style.ts
  client/src/components/LoginSlider/LoginSlider.tsx
  client/src/components/LoginSlider/style.ts
  client/src/components/LoginSocial/LoginSocial.tsx
  client/src/components/LoginSocial/style.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Login/Signup.tsx
  client/src/pages/Login/style.ts
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Signup/style.ts
  client/src/types/user.ts
Labels: ✨ feature, [FE] 이수련, 💄 style

#70 [Client] tab 컴포넌트 제작
  client/src/App.tsx
  client/src/components/Tab/Tab.tsx
  client/src/components/Tab/style.ts
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/style.ts
Labels: ✨ feature, [FE] 이수련, 💄 style

#71 [Client] main 페이지 기본 완성
  client/package-lock.json
  client/package.json
  client/src/api/api.ts
  client/src/components/ImageCard/ImageCard.tsx
  client/src/components/Skeleton/ImageSkeleton.tsx
  client/src/components/SortTab/SortTab.tsx
  client/src/pages/Main/DummyData.ts
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/style.ts
Labels: ✨ feature, [FE] 송인선, 💄 style

#75 [Server] 생일 DTO 수정, exposedHeader 추가
  server/src/main/java/com/cocoa/catdog/config/CorsFilter.java
  server/src/main/java/com/cocoa/catdog/config/SecurityConfiguration.java
  server/src/main/java/com/cocoa/catdog/config/WebConfig.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserBirthDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserPatchDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserPostDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java
Labels: 🐛 bug, [BE] 김정민

#73 Be.feat kugnas
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java
  server/src/main/java/com/cocoa/catdog/comment/entity/Comment.java
  server/src/main/java/com/cocoa/catdog/comment/repository/CommentLikeRepository.java
  server/src/main/java/com/cocoa/catdog/comment/repository/CommentReportRepository.java
  server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/helper/controller/HelperController.java
  server/src/main/java/com/cocoa/catdog/helper/dto/HelperDto.java
  server/src/main/java/com/cocoa/catdog/helper/service/HelperService.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
  server/src/test/java/com/cocoa/catdog/comment/CommentServiceUnitTest.java
Labels: ✨ feature, [BE] 남상욱

#77 ♻️ refactor: response 코드변경
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
Labels: [BE] 남상욱, ♻️ refactor

#79 [Client] 글 작성 페이지 완성
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/article.ts
  client/src/components/Articles/PhotoPreview/PhotoPreview.tsx
  client/src/components/Articles/PhotoUpload/PhotoUpload.tsx
  client/src/components/Articles/PhotoUpload/style.ts
  client/src/components/Articles/WriteArticle/WriteArticle.tsx
  client/src/components/Articles/WriteArticle/style.ts
  client/src/components/Header/HeaderAfter.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/style.ts
  client/src/pages/Articles/NewArticle.tsx
  client/src/types/article.ts
  client/src/utills/FileValidCheck.ts
  client/tsconfig.json
Labels: ✨ feature, [FE] 김윤희, 💄 style

#81 [Server] cors 세팅 변경
  server/data/testdb.mv.db
  server/src/main/java/com/cocoa/catdog/config/CorsFilter.java
  server/src/main/java/com/cocoa/catdog/config/SecurityConfiguration.java
  server/src/main/java/com/cocoa/catdog/config/WebConfig.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/resources/application-h2.yml
Labels: 🐛 bug, [BE] 김정민, ⚙️ setting

#86 [Client] main 페이지 api 최신 버전 및 정렬 적용
  client/src/api/api.ts
  client/src/assets/img/subscribe-icon-ver01.svg
  client/src/assets/img/subscribe-icon-ver02.svg
  client/src/components/SortTab/SortTab.tsx
  client/src/custom.d.ts
  client/src/pages/Main/Main.tsx
  client/src/utills/ScrollToTop.tsx
Labels: ✨ feature, [FE] 송인선, 💄 style

#88 Be.feat kugnas modify
  server/src/main/java/com/cocoa/catdog/advice/GlobalExceptionAdvice.java
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/entity/Like.java
  server/src/main/java/com/cocoa/catdog/article/entity/Report.java
  server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java
  server/src/main/java/com/cocoa/catdog/article/repository/LikeRepository.java
  server/src/main/java/com/cocoa/catdog/article/repository/ReportRepository.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentDto.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
  server/src/main/java/com/cocoa/catdog/comment/entity/CommentReport.java
  server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java
  server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/helper/controller/HelperController.java
  server/src/main/java/com/cocoa/catdog/helper/dto/HelperDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserSimpleResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
Labels: 🐛 bug, ✨ feature, [BE] 남상욱

#89 [Client] 글 상세 페이지 1차 제작
  client/src/api/api.ts
  client/src/api/article.ts
  client/src/api/user.ts
  client/src/assets/img/arrow-circle-icon.svg
  client/src/assets/img/chat-icon.svg
  client/src/assets/img/heart-icon.svg
  client/src/assets/img/subscribe-simple-color-icon.svg
  client/src/assets/img/subscribe-simple-icon.svg
  client/src/components/Articles/WriteArticle/WriteArticle.tsx
  client/src/components/Avatar/style.ts
  client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx
  client/src/components/Detail/ArticleLikeAndSnack/style.ts
  client/src/components/Detail/CommentAdd/CommentAdd.tsx
  client/src/components/Detail/CommentAdd/style.ts
  client/src/components/Detail/Comments/Comments.tsx
  client/src/components/Detail/Comments/dummy.ts
  client/src/components/Detail/Comments/style.ts
  client/src/components/Detail/DetailArticle/DetailArticle.tsx
  client/src/components/Detail/DetailArticle/style.ts
  client/src/components/Detail/DetailSlider/DetailSlider.tsx
  client/src/components/Detail/DetailSlider/style.ts
  client/src/components/Detail/ReactionBtn/ReactionBtn.tsx
  client/src/components/Detail/ReactionBtn/style.ts
  client/src/components/Detail/SnackGiver/SnackGive.tsx
  client/src/components/Detail/SnackGiver/style.ts
  client/src/components/Login/LoginForm/LoginForm.tsx
  client/src/components/Login/LoginForm/style.ts
  client/src/components/Login/LoginSlider/LoginSlider.tsx
  client/src/components/Login/LoginSlider/style.ts
  client/src/components/Login/LoginSocial/LoginSocial.tsx
  client/src/components/Login/LoginSocial/style.ts
  client/src/components/Signup/SignupFormStep/StepForm.tsx
  client/src/components/Signup/SignupFormStep/style.ts
  client/src/components/Signup/SignupSuccessStep/StepSucess.tsx
  client/src/components/Signup/SignupTypeStep/StepType.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/utills/DisplayCreatedAt.ts
  client/src/utills/ShortenNumber.ts
  client/src/utills/useAutosizeTextArea.ts
Labels: ✨ feature, [FE] 이수련, ♻️ refactor, 💄 style

#90 [Client] 마이페이지 레이아웃 구현
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPageArticles.tsx
  client/src/pages/MyPage/MyPageComments.tsx
  client/src/pages/MyPage/MyPageSnacks.tsx
Labels: ✨ feature, [FE] 송인선

#91 [Client] 수정 기능 구현
  client/src/api/article.ts
  client/src/components/Articles/PhotoUpload/PhotoUpload.tsx
  client/src/components/Articles/WriteArticle/WriteArticle.tsx
  client/src/components/Articles/WriteArticle/style.ts
  client/src/pages/Articles/NewArticle.tsx
  client/src/types/article.ts
Labels: ✨ feature, [FE] 김윤희

#92 [Client] 로그인 시 리코일 전역 상태 저장 처리
  client/package-lock.json
  client/package.json
  client/src/_state/accessTokenState.tsx
  client/src/_state/isLoginState.tsx
  client/src/_state/refreshTokenState.tsx
  client/src/_state/userInfoState.tsx
  client/src/api/article.ts
  client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx
  client/src/components/Detail/DetailArticle/DetailArticle.tsx
  client/src/components/Detail/ReactionBtn/ReactionBtn.tsx
  client/src/index.tsx
  client/src/pages/Articles/NewArticle.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Login/Login.tsx
Labels: ✨ feature, [FE] 이수련, ⚙️ setting, 💄 style

#97 [Client] 상점 페이지 구현
  client/src/App.tsx
  client/src/api/shop.ts
  client/src/components/Checkbox/Checkbox.tsx
  client/src/components/Checkbox/style.ts
  client/src/components/ImageCard/ImageCard.tsx
  client/src/components/Shop/Calculator/CalcContent.tsx
  client/src/components/Shop/Calculator/Calculator.tsx
  client/src/components/Shop/Calculator/style.ts
  client/src/components/Shop/Items/Item/Item.tsx
  client/src/components/Shop/Items/Item/style.ts
  client/src/components/Shop/Items/items.tsx
  client/src/components/Shop/ShopInfo/ShopInfo.tsx
  client/src/components/Shop/ShopInfo/style.ts
  client/src/pages/Shop/Shop.tsx
  client/src/pages/Shop/style.ts
  client/src/types/shop.ts
Labels: ✨ feature, [FE] 김윤희, 💄 style

#102 [Client] 헤더, 메인 페이지 로그인 분기 적용 및 레이아웃 수정
  client/src/App.tsx
  client/src/api/api.ts
  client/src/api/article.ts
  client/src/components/Header/Header.tsx
  client/src/components/Header/HeaderAfter.tsx
  client/src/components/Header/HeaderBefore.tsx
  client/src/components/Header/LogoutPopup.tsx
  client/src/components/Header/MenuList.tsx
  client/src/components/Header/style.tsx
  client/src/components/SortTab/SortTab.tsx
  client/src/pages/Main/Main.tsx
Labels: ✨ feature, [FE] 송인선, 💄 style

#106 Be.feat img
  server/.gitignore
  server/build.gradle
  server/data/testdb.mv.db
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/config/CommonUtils.java
  server/src/main/java/com/cocoa/catdog/config/aws/AWSConfig.java
  server/src/main/java/com/cocoa/catdog/config/aws/AmazonS3Component.java
  server/src/main/java/com/cocoa/catdog/config/aws/S3Uploader.java
  server/src/main/resources/application.yml
Labels: ✨ feature

#107 [Client] 상점 페이지 반응형 구현
  client/src/components/Shop/Calculator/CalcContent.tsx
  client/src/components/Shop/Calculator/style.ts
  client/src/components/Shop/Items/Item/Item.tsx
  client/src/components/Shop/Items/Item/style.ts
  client/src/components/Shop/Items/items.tsx
  client/src/components/Shop/ShopInfo/style.ts
Labels: [FE] 김윤희, 💄 style

#101 🐛 bug: 댓글조회오류(게시물이 달라도 같은 댓글들 조회) 수정
  server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java
  server/src/main/java/com/cocoa/catdog/comment/repository/CommentRepository.java
  server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java
Labels: 🐛 bug, [BE] 남상욱

#108 [Server] 마이페이지, 프로필 구현
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/comment/controller/CommentController.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
  server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java
  server/src/main/java/com/cocoa/catdog/comment/repository/CommentRepository.java
  server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/order/controller/OrderController.java
  server/src/main/java/com/cocoa/catdog/order/entity/Order.java
  server/src/main/java/com/cocoa/catdog/order/repository/OrderRepository.java
  server/src/main/java/com/cocoa/catdog/order/service/OrderService.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserProfileResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/mapper/UserMapper.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java
Labels: ✨ feature, [BE] 남상욱

#111 Be.feat search article by content containing search keyword
  server/.gitignore
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/user/repository/UserRepository.java
Labels: ✨ feature

#110 [Client] 글 상세 페이지 api 연결 1차
  client/src/api/article.ts
  client/src/api/comment.ts
  client/src/api/subscribe.ts
  client/src/assets/img/github-icon.svg
  client/src/assets/img/google-icon.svg
  client/src/assets/img/naver-icon.svg
  client/src/assets/img/subscribe-icon-ver01.svg
  client/src/assets/img/subscribe-icon-ver02.svg
  client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx
  client/src/components/Detail/CommentAdd/CommentAdd.tsx
  client/src/components/Detail/Comments/Comments.tsx
  client/src/components/Detail/Comments/dummy.ts
  client/src/components/Detail/Comments/style.ts
  client/src/components/Detail/ExtraFeatureModal.tsx/ExtraFeatureModal.tsx
  client/src/components/Detail/ExtraFeatureModal.tsx/style.ts
  client/src/components/Detail/ReactionBtn/ReactionBtn.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/style.ts
  client/src/types/article.ts
  client/src/types/comment.ts
Labels: ✨ feature, [FE] 이수련, 💄 style

#112 [Server] 구글 OAtuh2 로그인 기능 구현
  server/.gitignore
  server/build.gradle
  server/data/testdb.mv.db
  server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/cocoa/catdog/config/ApplicationConfig.java
  server/src/main/java/com/cocoa/catdog/config/CorsFilter.java
  server/src/main/java/com/cocoa/catdog/config/SecurityConfiguration.java
  server/src/main/java/com/cocoa/catdog/user/controller/LoginController.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/repository/UserRepository.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
  server/src/main/resources/application-h2.yml
  server/src/main/resources/templates/login.html
  server/src/main/resources/templates/my-page.html
  server/src/main/resources/templates/receive-token.html
Labels: ✨ feature, [BE] 김정민

#117 [Client] 글 상세 페이지 케이스 대응
  client/src/api/comment.ts
  client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx
  client/src/components/Detail/CommentAdd/CommentAdd.tsx
  client/src/components/Detail/Comments/Comments.tsx
  client/src/components/Detail/ExtraFeatureModal.tsx/ExtraFeatureModal.tsx
  client/src/components/Detail/ReactionBtn/ReactionBtn.tsx
Labels: ✨ feature, [FE] 이수련

#119 [Client] 상점 페이지 로직 수정
  client/src/api/shop.ts
  client/src/components/Checkbox/Checkbox.tsx
  client/src/components/Checkbox/style.ts
  client/src/components/Shop/Calculator/Calculator.tsx
  client/src/components/Shop/Items/Item/Item.tsx
  client/src/components/Shop/Items/Item/style.ts
  client/src/components/Shop/Items/items.tsx
  client/src/pages/Shop/Shop.tsx
  client/src/pages/Shop/style.ts
Labels: 🐛 bug, ✨ feature, [FE] 김윤희

#121 [Client] 디테일/ 로그인 페이지 api 연결 2차
  client/public/assets/no-comments-clipart.png
  client/public/favicon.ico
  client/src/App.tsx
  client/src/api/article.ts
  client/src/api/comment.ts
  client/src/api/user.ts
  client/src/components/Detail/CommentAdd/CommentAdd.tsx
  client/src/components/Detail/CommentEditModal/CommentEditModal.tsx
  client/src/components/Detail/CommentEditModal/style.ts
  client/src/components/Detail/Comments/Comments.tsx
  client/src/components/Detail/Comments/style.ts
  client/src/components/Detail/ExtraFeatureModal.tsx/ExtraFeatureModal.tsx
  client/src/components/Header/LogoutPopup.tsx
  client/src/components/Loading/Loading.tsx
  client/src/components/Loading/style.ts
  client/src/components/Login/FindPassword/FindPassword.tsx
  client/src/components/Login/FindPassword/style.ts
  client/src/pages/Articles/NewArticle.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/Login/Login.tsx
Labels: ✨ feature, [FE] 이수련

#122 [Client] 설정 페이지 1차 완료
  client/src/api/user.ts
  client/src/components/Articles/PhotoUpload/PhotoUpload.tsx
  client/src/components/Setting/ChangePassword/ChangePassword.tsx
  client/src/components/Setting/DeleteAccount/DeleteAccount.tsx
  client/src/components/Setting/EditProfile/EditProfile.tsx
  client/src/components/Setting/EditProfile/UserInfo/UserInfo.tsx
  client/src/components/Setting/EditProfile/UserInfo/style.ts
  client/src/components/Setting/EditProfile/style.ts
  client/src/pages/Setting/Setting.tsx
  client/src/pages/Setting/style.ts
  client/src/types/article.ts
  client/src/types/setting.ts
  client/src/types/user.ts
  client/src/utills/CompressAndUploadFile.ts
Labels: ✨ feature, [FE] 김윤희, 💄 style

#125 [Client] 마이페이지 기능 구현 1차 완료
  client/src/App.tsx
  client/src/api/mypage.ts
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPageArticles.tsx
  client/src/pages/MyPage/MyPageComments.tsx
  client/src/pages/MyPage/MyPageSnacks.tsx
  client/src/pages/MyPage/style.ts
  client/src/pages/Profiles/ProfileArticles.tsx
  client/src/pages/Profiles/ProfileSnacks.tsx
  client/src/pages/Profiles/style.ts
Labels: ✨ feature, [FE] 송인선, 💄 style

#128 ✨ feat: SSE 구현 및 비동기처리(V1)
  server/src/main/java/com/cocoa/catdog/CatdogApplication.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/config/AsyncConfig.java
  server/src/main/java/com/cocoa/catdog/message/EmitterRepository.java
  server/src/main/java/com/cocoa/catdog/message/EmitterRepositoryImpl.java
  server/src/main/java/com/cocoa/catdog/message/Event.java
  server/src/main/java/com/cocoa/catdog/message/EventListener.java
  server/src/main/java/com/cocoa/catdog/message/EventRepository.java
  server/src/main/java/com/cocoa/catdog/message/SseController.java
  server/src/main/java/com/cocoa/catdog/message/SseEmitterRepository.java
  server/src/main/java/com/cocoa/catdog/message/SseEmitterService.java
  server/src/main/java/com/cocoa/catdog/message/SseEventRepository.java
Labels: ✨ feature, [BE] 남상욱

#129 Be.feat dto
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
  server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java
  server/src/main/java/com/cocoa/catdog/item/controller/ItemController.java
  server/src/main/java/com/cocoa/catdog/item/service/ItemService.java
  server/src/main/java/com/cocoa/catdog/order/dto/OrderItemResponseDto.java
  server/src/main/java/com/cocoa/catdog/order/entity/OrderItem.java
  server/src/main/java/com/cocoa/catdog/order/mapper/OrderMapper.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserProfileResponseDto.java
  server/src/main/java/com/cocoa/catdog/wallet/controller/GiveTakeController.java
  server/src/main/java/com/cocoa/catdog/wallet/dto/GiveTakeDto.java
  server/src/main/java/com/cocoa/catdog/wallet/dto/GiveTakeResponseDto.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/GiveTake.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java
  server/src/main/java/com/cocoa/catdog/wallet/mapper/GiveTakeMapper.java
  server/src/main/java/com/cocoa/catdog/wallet/repository/GiveTakeRepository.java
  server/src/main/java/com/cocoa/catdog/wallet/service/GiveTakeService.java
Labels: ✨ feature, [BE] 남상욱

#131 ♻️ refactor: 이미지 업로드 리팩터 #105
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleImgDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/entity/ArticleImg.java
  server/src/main/java/com/cocoa/catdog/article/mapper/ArticleImgMapper.java
  server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleImgRepository.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/article/service/FileHandler.java
  server/src/main/java/com/cocoa/catdog/config/CommonUtils.java
  server/src/main/java/com/cocoa/catdog/config/aws/S3Uploader.java
Labels: ♻️ refactor

#133 Be.feat kugnas
  server/src/main/java/com/cocoa/catdog/CatdogApplication.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
  server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java
  server/src/main/java/com/cocoa/catdog/config/AsyncConfig.java
  server/src/main/java/com/cocoa/catdog/item/controller/ItemController.java
  server/src/main/java/com/cocoa/catdog/item/service/ItemService.java
  server/src/main/java/com/cocoa/catdog/message/EmitterRepository.java
  server/src/main/java/com/cocoa/catdog/message/EmitterRepositoryImpl.java
  server/src/main/java/com/cocoa/catdog/message/Event.java
  server/src/main/java/com/cocoa/catdog/message/EventListener.java
  server/src/main/java/com/cocoa/catdog/message/EventRepository.java
  server/src/main/java/com/cocoa/catdog/message/SseController.java
  server/src/main/java/com/cocoa/catdog/message/SseEmitterRepository.java
  server/src/main/java/com/cocoa/catdog/message/SseEmitterService.java
  server/src/main/java/com/cocoa/catdog/message/SseEventRepository.java
  server/src/main/java/com/cocoa/catdog/order/dto/OrderItemResponseDto.java
  server/src/main/java/com/cocoa/catdog/order/entity/OrderItem.java
  server/src/main/java/com/cocoa/catdog/order/mapper/OrderMapper.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserProfileResponseDto.java
  server/src/main/java/com/cocoa/catdog/wallet/controller/GiveTakeController.java
  server/src/main/java/com/cocoa/catdog/wallet/dto/GiveTakeDto.java
  server/src/main/java/com/cocoa/catdog/wallet/dto/GiveTakeResponseDto.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/GiveTake.java
  server/src/main/java/com/cocoa/catdog/wallet/entity/Wallet.java
  server/src/main/java/com/cocoa/catdog/wallet/mapper/GiveTakeMapper.java
  server/src/main/java/com/cocoa/catdog/wallet/repository/GiveTakeRepository.java
  server/src/main/java/com/cocoa/catdog/wallet/service/GiveTakeService.java
Labels: ✨ feature, [BE] 남상욱

#132 [Client] 소셜 로그인관련 1차 구현
  client/src/App.tsx
  client/src/api/user.ts
  client/src/components/Header/Header.tsx
  client/src/components/Login/LoginSocial/LoginSocial.tsx
  client/src/components/Login/LoginSocial/style.ts
  client/src/components/SocialForm/SocialForm.tsx
  client/src/components/SocialForm/style.ts
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Login/Login.tsx
  client/src/pages/Signup/Signup.tsx
  client/src/pages/Social/Social.tsx
  client/src/pages/Social/style.ts
Labels: ✨ feature, [FE] 이수련

#134 ✨ feat: 이미지링크로 반환하도록 구현
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java
  server/src/main/java/com/cocoa/catdog/comment/dto/CommentResponseDto.java
  server/src/main/java/com/cocoa/catdog/comment/mapper/CommentMapper.java
Labels: ✨ feature, [BE] 남상욱

#136 ✨ feat: 구글 로그인 구현 완료 #109
  server/.gitignore
  server/data/testdb.mv.db
  server/data/testdb.trace.db
  server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/cocoa/catdog/config/ApplicationConfig.java
  server/src/main/java/com/cocoa/catdog/user/controller/LoginController.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserPatchDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
  server/src/main/resources/application-h2.yml
  server/src/main/resources/application.yml
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/login.html
  server/src/main/resources/templates/modify.html
Labels: ✨ feature, [BE] 김정민

#138 [Client] 소개 페이지 & 배너 컴포넌트 제작
  client/public/assets/banner-clipart.png
  client/src/App.tsx
  client/src/assets/style/GloabalVariables.ts
  client/src/components/Banner/Banner.tsx
  client/src/components/Banner/style.ts
  client/src/components/Introduce/ProjectIntro/ProjectIntro.tsx
  client/src/components/Introduce/ProjectIntro/style.ts
  client/src/components/Introduce/RollingPaper/RollingPaper.tsx
  client/src/components/Introduce/RollingPaper/style.ts
  client/src/pages/Introduce/Introduce.tsx
  client/src/pages/Introduce/style.ts
  client/src/pages/Main/Main.tsx
Labels: ✨ feature, [FE] 이수련

#141 [Client] 글 작성 페이지 수정
  client/src/components/Articles/PhotoPreview/PhotoPreview.tsx
  client/src/components/Articles/PhotoUpload/PhotoUpload.tsx
  client/src/components/Articles/WriteArticle/WriteArticle.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/style.ts
  client/src/pages/Articles/NewArticle.tsx
Labels: ✨ feature, [FE] 김윤희, 💄 style

#142 Feat/give
  client/src/api/article.ts
  client/src/components/Banner/style.ts
  client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx
  client/src/components/Detail/ReactionBtn/ReactionBtn.tsx
  client/src/components/Detail/SnackGiver/SnackGiver.tsx
Labels: ✨ feature, [FE] 이수련

#143 [Client] 본인 계정 간식 주기 막음
  client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx
  client/src/components/Detail/SnackGiver/SnackGiver.tsx
  client/src/components/Modal/style.ts
Labels: ✨ feature, [FE] 이수련, 💄 style

#144 [Client] 글 작성 페이지 오류 수정
  client/src/App.tsx
  client/src/components/Articles/PhotoUpload/PhotoUpload.tsx
  client/src/components/Articles/WriteArticle/WriteArticle.tsx
  client/src/pages/Articles/NewArticle.tsx
Labels: 🐛 bug, [FE] 김윤희

#145 [Client] 설정 페이지 비밀번호 변경, 회원 탈퇴 수정
  client/src/api/user.ts
  client/src/components/Input/Input.tsx
  client/src/components/Setting/ChangePassword/ChangePassword.tsx
  client/src/components/Setting/DeleteAccount/DeleteAccount.tsx
  client/src/pages/Setting/Setting.tsx
Labels: ✨ feature, [FE] 김윤희

#147 [Client] 상품 수량이 재고보다 많거나 음수인 경우 제한
  client/src/components/Shop/Items/Item/Item.tsx
  client/src/pages/Shop/Shop.tsx
Labels: ✨ feature, [FE] 김윤희

#150 [Server] 사료주고받기 오류수정, 글검색기능구현, 글조회queryDsl로 리팩토링
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepository.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustom.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/config/QuerydslConfiguration.java
  server/src/main/java/com/cocoa/catdog/exception/ExceptionCode.java
  server/src/main/java/com/cocoa/catdog/wallet/service/GiveTakeService.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: ✨ feature, [BE] 남상욱, ♻️ refactor

#148 [Client] 마이페이지 기능 구현 2차 완료
  client/src/api/subscribe.ts
  client/src/components/MyPage/FollowPopUp.tsx
  client/src/components/MyPage/FollowerPopUp.tsx
  client/src/components/MyPage/UnFollowPopUp.tsx
  client/src/components/NoContent/NoContent.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/style.ts
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPageArticles.tsx
  client/src/pages/MyPage/MyPageComments.tsx
  client/src/pages/MyPage/MyPageSnacks.tsx
  client/src/pages/MyPage/style.ts
  client/src/pages/Profiles/ProfileArticles.tsx
  client/src/pages/Profiles/ProfileSnacks.tsx
  client/src/pages/Profiles/Profiles.tsx
  client/src/pages/Profiles/style.ts
Labels: ✨ feature, [FE] 송인선, 💄 style

#151 유저 이미지 업로드 수정 삭제 기능 추가
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/config/aws/AWSConfig.java
  server/src/main/java/com/cocoa/catdog/config/aws/S3Service.java
  server/src/main/java/com/cocoa/catdog/helper/service/HelperService.java
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserPatchDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserPostDto.java
  server/src/main/java/com/cocoa/catdog/user/dto/UserResponseDto.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/main/resources/application.yml
Labels: ✨ feature, [BE] 조지선

#152 [Server] ♻️ fix: oauth redirect 주소 수정
  server/src/main/resources/application.yml
  server/src/main/resources/templates/login.html
Labels: 🐛 bug, [BE] 김정민

#153 🐛 fix: 이미지 업이 회원가입, 회원수정 되도록 버그 수정 #105
  server/src/main/java/com/cocoa/catdog/user/controller/UserController.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
Labels: 🐛 bug, [BE] 조지선

#154 [Client] 메인 페이지 좋아요, 간식 실시간 적용 및 마이페이지 에러 해결
  client/src/_state/mainLIstState.tsx
  client/src/components/Detail/ArticleLikeAndSnack/ArticleLikeAndSnack.tsx
  client/src/components/TopButton/TopButton.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/MyPage/MyPageArticles.tsx
  client/src/pages/MyPage/MyPageSnacks.tsx
  client/src/pages/Profiles/ProfileSnacks.tsx
Labels: 🐛 bug, ✨ feature, [FE] 송인선

#156 [Server] 신고에 따른 블락처리
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/entity/Article.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustom.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/user/entity/User.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
Labels: ✨ feature, [BE] 남상욱

#158 [Server] ♻️ fix: oauth 리다이렉트 방식 변경, 패스워드 변경 기능 수정 🐛 bug
  server/data/testdb.mv.db
  server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/cocoa/catdog/user/service/UserService.java
Labels: ✨ feature, [BE] 김정민

#159 [Server] ♻️ fix: SMTP 비밀번호 환경변수 적용
  server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/resources/application.yml
Labels: ✨ feature, [BE] 김정민

#161 🐛 bug: 글목록 중복오류 수정
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java
Labels: 🐛 bug, [BE] 남상욱

#162 ♻️ fix: 가입상태와 기본정보유무에 따른 파라미터 추가
  server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/resources/application.yml
Labels: ✨ feature, [BE] 김정민

#164 🐛 bug: 글목록 중복오류 수정
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustom.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
Labels: 🐛 bug, [BE] 남상욱
