Repository codestates-seb/seb40_main_016, pull requests merged in 2022-12, with the labels that each got.

#165 [Client] 구글 소셜 로그인 연결
  client/src/App.tsx
  client/src/api/user.ts
  client/src/assets/img/github-icon.svg
  client/src/assets/img/google-icon.svg
  client/src/assets/img/naver-icon.svg
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/style.tsx
  client/src/components/Login/LoginSocial/LoginSocial.tsx
  client/src/components/Login/LoginSocial/style.ts
  client/src/pages/InfoSocialSet/InfoSocialSet.tsx
  client/src/pages/InfoSocialSet/style.ts
  client/src/pages/Login/Login.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/PendingLogin/PendingLogin.tsx
  client/src/pages/PendingLogin/styled.ts
Labels: ✨ feature, [FE] 이수련

#167 [Client] QA 처리
  client/public/assets/not-found-bg.jpg
  client/src/components/Detail/ConfirmDeleteModal/ConfirmDeleteModal.tsx
  client/src/components/Detail/ConfirmDeleteModal/style.ts
  client/src/components/Detail/ExtraFeatureModal.tsx/ExtraFeatureModal.tsx
  client/src/components/Detail/SnackGiver/SnackGiver.tsx
  client/src/components/Loading/Loading.tsx
  client/src/pages/Detail/Detail.tsx
  client/src/pages/Detail/style.ts
  client/src/pages/NotFound/NotFound.tsx
  client/src/pages/NotFound/style.ts
Labels: ✨ feature, [FE] 이수련

#168 🐛 bug: 마이페이지 중복오류 수정
  server/src/main/java/com/cocoa/catdog/article/Dto/ArticleDto.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/mapper/ArticleMapper.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustom.java
  server/src/main/java/com/cocoa/catdog/article/repository/ArticleRepositoryCustomImpl.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
Labels: 🐛 bug, [BE] 남상욱

#169 [Client] 메인페이지 글 검색 api 연결 및 기타 컴포넌트 css 수정
  client/src/api/article.ts
  client/src/components/Balloon/Balloon.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/style.tsx
  client/src/components/OuterContainer/OuterConainer.tsx
  client/src/components/SortTab/SortTab.tsx
  client/src/components/TopButton/TopButton.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/style.ts
Labels: ✨ feature, [FE] 송인선

#170 ♻️ fix: 구글 리다이랙션 주소 배포용으로 변경
  server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
Labels: [BE] 김정민

#176 [Client] 메인페이지 검색, 무한스크롤 에러 해결, 탑버튼 수정
  client/src/components/Header/Header.tsx
  client/src/components/TopButton/TopButton.tsx
  client/src/pages/Main/Main.tsx
Labels: 🐛 bug, [FE] 송인선

#178 [Client] 무한스크롤 리팩토링, 게시물탭 중복 에러 해결
  client/src/api/mypage.ts
  client/src/components/Header/Header.tsx
  client/src/pages/Main/Main.tsx
  client/src/pages/Main/style.ts
  client/src/pages/MyPage/MyPage.tsx
  client/src/pages/MyPage/MyPageArticles.tsx
  client/src/pages/MyPage/MyPageComments.tsx
  client/src/pages/MyPage/MyPageSnacks.tsx
  client/src/pages/Profiles/ProfileArticles.tsx
  client/src/pages/Profiles/ProfileSnacks.tsx
  client/src/pages/Profiles/Profiles.tsx
Labels: 🐛 bug, ✨ feature, [FE] 송인선, ♻️ refactor, 💄 style

#179 [Client] 소개 페이지 완료
  client/public/assets/change-password.gif
  client/public/assets/delete-account.gif
  client/public/assets/detail.gif
  client/public/assets/find-password.gif
  client/public/assets/header.png
  client/public/assets/imageCard.png
  client/public/assets/login.gif
  client/public/assets/logout.gif
  client/public/assets/main.webp
  client/public/assets/my-page-filter.png
  client/public/assets/my-page-sort.png
  client/public/assets/my-page.gif
  client/public/assets/my-page.png
  client/public/assets/other-profile.gif
  client/public/assets/profile-change.gif
  client/public/assets/search.gif
  client/public/assets/shop.gif
  client/public/assets/signup.gif
  client/public/assets/social-login.gif
  client/public/assets/update-article.gif
  client/public/assets/write-article.gif
  client/src/components/Introduce/ProjectIntro/ProjectIntro.tsx
  client/src/components/Introduce/ProjectIntro/style.ts
  client/src/pages/Introduce/style.ts
Labels: ✨ feature, [FE] 김윤희

#180 [Client] 피드백받은 부분 수정
  client/src/components/Articles/PhotoUpload/style.ts
  client/src/components/Articles/WriteArticle/WriteArticle.tsx
  client/src/components/Modal/style.ts
  client/src/components/Setting/DeleteAccount/DeleteAccount.tsx
  client/src/components/Shop/Items/Item/Item.tsx
  client/src/pages/Shop/Shop.tsx
Labels: 🐛 bug, ✨ feature, [FE] 김윤희, 💄 style

#182 ♻️ fix: 구글 리다이랙션 주소 SSL 적용, 시큐리티 OPTIONS 추가
  server/src/main/java/com/cocoa/catdog/auth/handler/OAuth2MemberSuccessHandler.java
  server/src/main/java/com/cocoa/catdog/config/SecurityConfiguration.java
  server/src/main/resources/application-h2.yml
Labels: [BE] 김정민, 💚chores

#189 [Client] 구독 알림 기능 구현, QA 피드백 반영
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Footer/Footer.tsx
  client/src/components/Header/Header.tsx
  client/src/components/Header/MenuList.tsx
  client/src/components/MyPage/FollowPopUp.tsx
  client/src/components/MyPage/FollowerPopUp.tsx
  client/src/components/MyPage/SnackPopUp.tsx
  client/src/components/MyPage/UnFollowPopUp.tsx
  client/src/components/SubAlert/SubAlert.tsx
  client/src/pages/MyPage/MyPageArticles.tsx
  client/src/pages/MyPage/MyPageSnacks.tsx
  client/src/pages/MyPage/style.ts
  client/src/pages/Profiles/ProfileArticles.tsx
  client/src/pages/Profiles/ProfileSnacks.tsx
  client/src/pages/Profiles/Profiles.tsx
  client/src/pages/Profiles/style.ts
Labels: 🐛 bug, ✨ feature, [FE] 송인선, 💄 style

#190 [Server] 알림기능 구현 및 버그수정
  server/build.gradle
  server/src/main/java/com/cocoa/catdog/CatdogApplication.java
  server/src/main/java/com/cocoa/catdog/article/controller/ArticleController.java
  server/src/main/java/com/cocoa/catdog/article/service/ArticleService.java
  server/src/main/java/com/cocoa/catdog/comment/service/CommentService.java
  server/src/main/java/com/cocoa/catdog/message/EventListener.java
  server/src/main/java/com/cocoa/catdog/message/SseEmitterRepository.java
  server/src/main/java/com/cocoa/catdog/message/SseEventRepository.java
  server/src/main/java/com/cocoa/catdog/message/event/Event.java
  server/src/main/java/com/cocoa/catdog/message/event/EventDto.java
  server/src/main/java/com/cocoa/catdog/message/event/EventListener.java
  server/src/main/java/com/cocoa/catdog/message/event/EventMapper.java
  server/src/main/java/com/cocoa/catdog/message/event/EventRepository.java
  server/src/main/java/com/cocoa/catdog/message/event/EventService.java
  server/src/main/java/com/cocoa/catdog/message/event/FileConverter.java
  server/src/main/java/com/cocoa/catdog/message/kafka/KafkaArticleDto.java
  server/src/main/java/com/cocoa/catdog/message/kafka/KafkaConsumer.java
  server/src/main/java/com/cocoa/catdog/message/kafka/KafkaConsumerConfig.java
  server/src/main/java/com/cocoa/catdog/message/kafka/KafkaProducer.java
  server/src/main/java/com/cocoa/catdog/message/kafka/KafkaProducerConfig.java
  server/src/main/java/com/cocoa/catdog/message/sse/EmitterRepository.java
  server/src/main/java/com/cocoa/catdog/message/sse/EmitterRepositoryImpl.java
  server/src/main/java/com/cocoa/catdog/message/sse/SseController.java
  server/src/main/java/com/cocoa/catdog/message/sse/SseEmitterService.java
  server/src/main/java/com/cocoa/catdog/user/service/FollowService.java
  server/src/main/java/com/cocoa/catdog/wallet/service/GiveTakeService.java
  server/src/main/resources/application.yml
Labels: 🐛 bug, ✨ feature, [BE] 남상욱

#191 ✨ feat: url을 s3 -> cdn 주소로 수정
  server/src/main/java/com/cocoa/catdog/config/aws/S3Service.java
  server/src/main/resources/application.yml
Labels: ✨ feature, [BE] 남상욱
